models:
  my_project:
    # Config indicated by + and applies to all files under models/example/
    _stg:
      +materialized: view
      +schema: _stg
      +database: store
    store_analytics:
      +materialized: table
      +schema: _intermediate
      +database: store
    fact:
      +materialized: table
      +schema: fact
      +database: store
    mart:
      +materialized: table
      +schema: mart
      +database: store